// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hchhvqlflqaelxvrcuxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaGh2cWxmbHFhZWx4dnJjdXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODE0MDQsImV4cCI6MjA2OTM1NzQwNH0.-MqOYiNb0LOxgJdq--KEgvSk2y5yMVTU-S2JDnoNw5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});